apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: sba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: sit-bmw-model
          image: registry.cn-hangzhou.aliyuncs.com/dev_savage/sba-search:{version}
          ports:
            - name: http-port
              containerPort: 10005
          env:
            - name: spring_profiles_active
              value: k8s
      imagePullSecrets:
        - name: sbasecret